name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode Version
      run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app

    - name: Build and Test
      run: |
        xcodebuild clean test \
        -project EssentialFeed/EssentialFeed.xcodeproj \
        -scheme "CI" \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
