name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  ios-tests:
    name: Run iOS Tests
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Xcode Version to 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Verify Xcode Version
        run: xcodebuild -version

      - name: List Available Simulators
        run: xcrun simctl list

      - name: Run Tests
        run: |
          xcodebuild test -scheme "CI_macOS" -destination 'platform=macOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
