name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  ios-tests:
    name: Run iOS Tests
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.3 # Replace with your Xcode version

      - name: Install Dependencies
        run: |
          brew install cocoapods || true
          pod install --project-directory=YourProjectDirectory

      - name: Run iOS Tests
        run: |
          xcodebuild test \
            -scheme YourIOSScheme \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' \
            -testPlan YourIOSTestPlan.xctestplan \
            | xcpretty

  macos-tests:
    name: Run macOS Tests
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.3 # Replace with your Xcode version

      - name: Run macOS Tests
        run: |
          xcodebuild test \
            -scheme YourMacOSScheme \
            -destination 'platform=macOS' \
            -testPlan YourMacOSTestPlan.xctestplan \
            | xcpretty


jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Xcode Version to 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Verify Xcode Version
        run: xcodebuild -version

      - name: Build and Test
        run: |
          xcodebuild clean test \
            -project EssentialFeed.xcodeproj \
            -scheme "CI_macOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -destination 'platform=macOS,arch=x86_64'

          xcodebuild clean test \
            -project EssentialFeed.xcodeproj \
            -scheme "CI_iOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0'
