name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  ios-tests:
    name: Run Tests
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Xcode Version to 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Verify Xcode Version
        run: xcodebuild -version

      - name: Run macOS Tests
        run: |
          xcodebuild test -scheme "CI_macOS" -destination 'platform=macOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Download iOS Platform
        run: xcodebuild -downloadPlatform iOS -verbose

      - name: Run iOS Tests
        run: |
          xcodebuild test -workspace EssentialApp.xcworkspace -scheme "CI_iOS" -destination 'platform=iOS Simulator,name=iPhone 16' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
